 export const SETUSERSTATE = 'USERSTATE'; 
 export const  FETCH_ASSETS_REQUEST = 'FETCH_ASSETS_REQUEST'
 export const FETCH_ASSETS_SUCESS = 'FETCH_ASSETS_SUCESS'
 export const FETCH_ASSETS_FAILURE = 'FETCH_ASSETS_FAILURE'
 

 //Issue asset 
 export const ISSUE_ASSET_REQUEST = 'ISSUE_ASSET_REQUEST'
 export const ISSUE_ASSET_SUCCESS = 'ISSUE_ASSET_SUCCESS'
 export const ISSUE_ASSET_FAILURE = 'ISSUE_ASSET_FAILURE '


 //Return assets
 export const RETURN_ASSET_REQUEST = 'RETURN_ASSET_REQUEST'
 export const RETURN_ASSET_SUCCESS = 'RETURN_ASSET_SUCCESS'
 export const RETURN_ASSET_FAILURE = 'RETURN_ASSET_FAILURE '


 //Get people action
 export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST';
 export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';
 export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';


 //Delete Item Actions
 export const DELETE_ASSET_REQUEST = 'DELETE_ASSET_REQUEST';
 export const DELETE_ASSET_FAILURE = 'DELETE_ASSET_FAILURE';
 export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
 