 export const SETUSERSTATE = 'USERSTATE'; 
 export const  FETCH_ASSETS_REQUEST = 'FETCH_ASSETS_REQUEST'
 export const FETCH_ASSETS_SUCESS = 'FETCH_ASSETS_SUCESS'
 export const FETCH_ASSETS_FAILURE = 'FETCH_ASSETS_FAILURE'
 

 //Issue asset 
 export const ISSUE_ASSET_REQUEST = 'ISSUE_ASSET_REQUEST'
 export const ISSUE_ASSET_SUCCESS = 'ISSUE_ASSET_SUCCESS'
 export const ISSUE_ASSET_FAILURE = 'ISSUE_ASSET_FAILURE '


 //Return assets
 export const RETURN_ASSET_REQUEST = 'RETURN_ASSET_REQUEST'
 export const RETURN_ASSET_SUCCESS = 'RETURN_ASSET_SUCCESS'
 export const RETURN_ASSET_FAILURE = 'RETURN_ASSET_FAILURE '



 
 //Search assets
 export const SEARCH_ASSET_REQUEST = 'SEARCH_ASSET_REQUEST'
 export const SEARCH_ASSET_SUCCESS = 'SEARCH_ASSET_SUCCESS'
 export const SEARCH_ASSET_FAILURE = 'SEARCH_ASSET_FAILURE '


 //Get people action
 export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST';
 export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';
 export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';


 //Delete Item Actions
 export const DELETE_ASSET_REQUEST = 'DELETE_ASSET_REQUEST';
 export const DELETE_ASSET_FAILURE = 'DELETE_ASSET_FAILURE';
 export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
 
  //Location actions
  export const LOCATION_REQUEST = 'LOCATION_REQUEST';
  export const LOCATION_REQUEST_FAILURE = 'LOCATION_REQUEST_FAILURE';
  export const LOCATION_REQUEST_SUCCESS = 'LOCATION_REQUEST_SUCCESS';


  //Category actions
  export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
  export const CATEGORY_REQUEST_FAILURE = 'CATEGORY_REQUEST_FAILURE';
  export const CATEGORY_REQUEST_SUCCESS = 'CATEGORY_REQUEST_SUCCESS';




  //get Brands Type
  export const BRAND_TYPE_REQUEST = 'BRAND_TYPE_REQUEST';
  export const BRAND_TYPE_REQUEST_SUCCESS = 'BRAND_TYPE_REQUEST_SUCCESS';
//   export const BRAND_TYPE_REQUEST_SUCCESS = 'BRAND_TYPE_REQUEST_SUCCESS';



  //get Brands 
  export const BRAND_REQUEST = 'BRAND_REQUEST';
  export const BRAND_REQUEST_SUCCESS = 'BRAND_REQUEST_SUCCESS';
//   export const BRAND_REQUEST_SUCCESS = 'BRAND_TYPE_REQUEST_SUCCESS';



  //get Owner
  export const OWNER_REQUEST = 'OWNER_REQUEST';
  export const OWNER_REQUEST_SUCCESS = 'OWNER_REQUEST_SUCCESS';


  
  //get Status
  export const STATUS_REQUEST = 'STATUS_REQUEST';
  export const STATUS_REQUEST_SUCCESS = 'STATUS_REQUEST_SUCCESS';

  
  