 export const SETUSERSTATE = 'USERSTATE'; 
 export const  FETCH_ASSETS_REQUEST = 'FETCH_TODO_REQUEST'
 export const FETCH_ASSETS_SUCESS = 'FETCH_TODO_SUCESS'
 export const FETCH_ASSETS_FAILURE = 'FETCH_TODO_FAILURE'

 